package com.ruoyi.common.utils.oss;

import com.aliyun.oss.ClientException;
import com.aliyun.oss.OSS;
import com.aliyun.oss.OSSClientBuilder;
import com.aliyun.oss.OSSException;
import com.ruoyi.common.utils.file.FileUploadUtils;
import org.springframework.web.multipart.MultipartFile;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

public class AliYunOssUtil {

    private static String endpoint = OssConfiguration.getEndpoint();
    private static String accessKeyId = OssConfiguration.getAccessKeyId();
    private static String accessKeySecret = OssConfiguration.getAccessKeySecret();
    private static String bucketName = OssConfiguration.getBucketName();


    /**
     * 根据文件路径上传
     *
     * @param baseDir 相对应用的基目录
     * @param file    上传的文件
     * @return 文件名称
     * @throws IOException
     */
    public static final String upload(String baseDir, MultipartFile file) throws IOException {
        try {
            String fileName = FileUploadUtils.extractFilename(file);
            String objectName = FileUploadUtils.getPathFileName(baseDir, fileName);
            if (objectName.startsWith("/")) {
                objectName = objectName.substring(1, objectName.length());
            }
            OSS ossClient = new OSSClientBuilder().build(endpoint, accessKeyId, accessKeySecret);
            InputStream inputStream = file.getInputStream();
            // 创建PutObject请求。
            ossClient.putObject(bucketName, objectName, inputStream);
            return objectName;
        } catch (Exception e) {
            throw new IOException(e.getMessage(), e);
        }
    }

    public static void main(String[] args) throws Exception {

        String txt = "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2477, 'RVA管理', 0, 5, 'rva', NULL, NULL, 1, 0, 'M', '0', '0', NULL, 'tool', 'admin', '2021-08-11 17:31:20', '', NULL, 'RVA管理目录');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2478, '模块', 3727, 1, 'crud0_rva_module', 'rva/app/crud', NULL, 1, 0, 'C', '0', '0', 'crud0_rva_module', 'build', 'admin', '2021-08-11 17:31:20', 'admin', '2022-03-10 17:07:15', '模块0菜单');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2489, '对象', 3727, 2, 'crud1_rva_object', 'rva/app/crud', NULL, 1, 0, 'C', '0', '0', 'crud1_rva_object', 'build', 'admin', '2021-08-11 17:31:20', 'admin', '2022-03-03 13:26:59', '对象1菜单');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2500, '应用', 3727, 3, 'crud1_rva_app', 'rva/app/crud', NULL, 1, 0, 'C', '0', '0', 'crud1_rva_app', 'build', 'admin', '2021-08-11 17:31:20', 'admin', '2022-03-03 13:27:08', '应用1菜单');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2534, '视图', 3727, 4, 'crud4_rva_view', 'rva/app/crud', NULL, 1, 0, 'C', '0', '0', 'crud4_rva_view', 'build', 'admin', '2021-08-30 10:08:02', 'admin', '2022-03-03 13:27:17', '视图14菜单');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3680, '前端列表', 3727, 10, 'crud0_rva_fe_list', 'rva/app/crud', NULL, 1, 0, 'C', '0', '0', 'crud0_rva_fe_list', 'build', '1', '2022-02-24 16:57:49', 'admin', '2022-03-03 13:27:56', NULL);\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3696, '内容管理', 2477, 6, 'cms', NULL, NULL, 1, 0, 'M', '0', '0', '', 'education', 'admin', '2022-02-25 15:07:20', 'admin', '2022-03-03 13:28:07', '');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3712, '分类列表', 3696, 0, 'crud0_rva_uniapp_tablist', 'rva/app/crud', NULL, 1, 0, 'C', '0', '0', 'crud0_rva_uniapp_tablist', 'build', '1', '2022-02-26 10:02:47', 'admin', '2022-02-26 10:03:19', NULL);\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3713, '新建分类列表', 3712, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_uniapp_tablist', '#', 'admin', '2022-02-26 10:02:46', '', NULL, '新建分类列表按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3714, '新建分类列表-提交', 3713, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_uniapp_tablist_submit_create', '#', 'admin', '2022-02-26 10:02:47', '', NULL, '新建分类列表-提交按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3715, '新建分类列表-重置', 3713, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_uniapp_tablist_reset_create', '#', 'admin', '2022-02-26 10:02:47', '', NULL, '新建分类列表-重置按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3716, '新建分类列表-取消', 3713, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_uniapp_tablist_close_create', '#', 'admin', '2022-02-26 10:02:47', '', NULL, '新建分类列表-取消按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3717, '修改分类列表', 3712, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_uniapp_tablist', '#', 'admin', '2022-02-26 10:02:47', '', NULL, '修改分类列表按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3718, '修改分类列表-提交', 3717, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_uniapp_tablist_submit_update', '#', 'admin', '2022-02-26 10:02:47', '', NULL, '修改分类列表-提交按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3719, '修改分类列表-重置', 3717, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_uniapp_tablist_reset_update', '#', 'admin', '2022-02-26 10:02:47', '', NULL, '修改分类列表-重置按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3720, '修改分类列表-取消', 3717, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_uniapp_tablist_close_update', '#', 'admin', '2022-02-26 10:02:47', '', NULL, '修改分类列表-取消按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3721, '分类列表列表', 3712, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_uniapp_tablist', '#', 'admin', '2022-02-26 10:02:47', '', NULL, '分类列表列表按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3722, '分类列表列表-新建', 3721, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_uniapp_tablist_create', '#', 'admin', '2022-02-26 10:02:47', '', NULL, '分类列表列表-新建按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3723, '分类列表列表-修改', 3721, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_uniapp_tablist_update', '#', 'admin', '2022-02-26 10:02:47', '', NULL, '分类列表列表-修改按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3724, '分类列表列表-删除', 3721, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_uniapp_tablist_delete_inner', '#', 'admin', '2022-02-26 10:02:47', '', NULL, '分类列表列表-删除按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3725, '分类列表列表-删除', 3721, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_uniapp_tablist_delete_top', '#', 'admin', '2022-02-26 10:02:47', '', NULL, '分类列表列表-删除按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3726, '查询分类列表', 3712, 3, '', NULL, NULL, 1, 0, 'F', '0', '0', 's0_rva_uniapp_tablist', '#', 'admin', '2022-02-26 10:02:47', '', NULL, '查询分类列表按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3727, '元数据管理', 2477, 0, 'meta', NULL, NULL, 1, 0, 'M', '0', '0', NULL, 'dict', 'admin', '2022-03-03 13:25:46', '', NULL, '');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3728, '图表', 3727, 6, 'crud0_rva_chart', 'rva/app/crud', NULL, 1, 0, 'C', '0', '0', 'crud0_rva_chart', 'chart', '1', '2022-03-11 15:29:28', 'admin', '2022-03-11 15:29:59', NULL);\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3729, '新建图表', 3728, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_chart', '#', 'admin', '2022-03-11 15:29:27', '', NULL, '新建图表按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3730, '新建图表-提交', 3729, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_chart_submit_create', '#', 'admin', '2022-03-11 15:29:27', '', NULL, '新建图表-提交按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3731, '新建图表-重置', 3729, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_chart_reset_create', '#', 'admin', '2022-03-11 15:29:27', '', NULL, '新建图表-重置按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3732, '新建图表-取消', 3729, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_chart_close_create', '#', 'admin', '2022-03-11 15:29:27', '', NULL, '新建图表-取消按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3733, '修改图表', 3728, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_chart', '#', 'admin', '2022-03-11 15:29:27', '', NULL, '修改图表按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3734, '修改图表-提交', 3733, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_chart_submit_update', '#', 'admin', '2022-03-11 15:29:27', '', NULL, '修改图表-提交按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3735, '修改图表-重置', 3733, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_chart_reset_update', '#', 'admin', '2022-03-11 15:29:27', '', NULL, '修改图表-重置按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3736, '修改图表-取消', 3733, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_chart_close_update', '#', 'admin', '2022-03-11 15:29:27', '', NULL, '修改图表-取消按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3737, '图表列表', 3728, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_chart', '#', 'admin', '2022-03-11 15:29:27', '', NULL, '图表列表按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3738, '图表列表-新建', 3737, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_chart_create', '#', 'admin', '2022-03-11 15:29:27', '', NULL, '图表列表-新建按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3739, '图表列表-修改', 3737, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_chart_update', '#', 'admin', '2022-03-11 15:29:27', '', NULL, '图表列表-修改按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3740, '图表列表-删除', 3737, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_chart_delete_inner', '#', 'admin', '2022-03-11 15:29:27', '', NULL, '图表列表-删除按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3741, '图表列表-删除', 3737, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_chart_delete_top', '#', 'admin', '2022-03-11 15:29:27', '', NULL, '图表列表-删除按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3742, '查询图表', 3728, 3, '', NULL, NULL, 1, 0, 'F', '0', '0', 's0_rva_chart', '#', 'admin', '2022-03-11 15:29:27', '', NULL, '查询图表按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3789, '流程定义', 3727, 7, 'crud0_rva_process', 'rva/app/crud', NULL, 1, 0, 'C', '0', '0', 'crud0_rva_process', 'build', '1', '2022-03-22 12:12:53', '1', '2022-03-22 12:12:53', NULL);\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3790, '新建流程定义', 3789, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_process', '#', 'admin', '2022-03-22 12:12:54', '', NULL, '新建流程定义按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3791, '新建流程定义-提交', 3790, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_process_submit_create', '#', 'admin', '2022-03-22 12:12:54', '', NULL, '新建流程定义-提交按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3792, '新建流程定义-重置', 3790, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_process_reset_create', '#', 'admin', '2022-03-22 12:12:54', '', NULL, '新建流程定义-重置按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3793, '新建流程定义-取消', 3790, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_process_close_create', '#', 'admin', '2022-03-22 12:12:54', '', NULL, '新建流程定义-取消按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3794, '修改流程定义', 3789, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_process', '#', 'admin', '2022-03-22 12:12:54', '', NULL, '修改流程定义按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3795, '修改流程定义-提交', 3794, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_process_submit_update', '#', 'admin', '2022-03-22 12:12:54', '', NULL, '修改流程定义-提交按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3796, '修改流程定义-重置', 3794, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_process_reset_update', '#', 'admin', '2022-03-22 12:12:54', '', NULL, '修改流程定义-重置按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3797, '修改流程定义-取消', 3794, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_process_close_update', '#', 'admin', '2022-03-22 12:12:54', '', NULL, '修改流程定义-取消按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3798, '流程定义列表', 3789, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_process', '#', 'admin', '2022-03-22 12:12:54', '', NULL, '流程定义列表按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3799, '流程定义列表-新建', 3798, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_process_create', '#', 'admin', '2022-03-22 12:12:54', '', NULL, '流程定义列表-新建按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3800, '流程定义列表-修改', 3798, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_process_update', '#', 'admin', '2022-03-22 12:12:54', '', NULL, '流程定义列表-修改按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3801, '流程定义列表-删除', 3798, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_process_delete_inner', '#', 'admin', '2022-03-22 12:12:54', '', NULL, '流程定义列表-删除按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3802, '流程定义列表-删除', 3798, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_process_delete_top', '#', 'admin', '2022-03-22 12:12:54', '', NULL, '流程定义列表-删除按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3803, '查询流程定义', 3789, 3, '', NULL, NULL, 1, 0, 'F', '0', '0', 's0_rva_process', '#', 'admin', '2022-03-22 12:12:54', '', NULL, '查询流程定义按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3804, 'KPI', 3727, 9, 'crud0_rva_kpi', 'rva/app/crud', NULL, 1, 0, 'C', '0', '0', 'crud0_rva_kpi', 'build', '1', '2022-03-24 10:49:22', '1', '2022-03-24 10:49:22', NULL);\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3805, '新建KPI', 3804, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_kpi', '#', 'admin', '2022-03-24 10:49:23', '', NULL, '新建KPI按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3806, '新建KPI-提交', 3805, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_kpi_submit_create', '#', 'admin', '2022-03-24 10:49:23', '', NULL, '新建KPI-提交按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3807, '新建KPI-重置', 3805, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_kpi_reset_create', '#', 'admin', '2022-03-24 10:49:23', '', NULL, '新建KPI-重置按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3809, '新建KPI-取消', 3805, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_kpi_close_create', '#', 'admin', '2022-03-24 10:49:23', '', NULL, '新建KPI-取消按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3810, '修改KPI', 3804, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_kpi', '#', 'admin', '2022-03-24 10:49:23', '', NULL, '修改KPI按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3811, '修改KPI-提交', 3810, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_kpi_submit_update', '#', 'admin', '2022-03-24 10:49:23', '', NULL, '修改KPI-提交按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3812, '修改KPI-重置', 3810, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_kpi_reset_update', '#', 'admin', '2022-03-24 10:49:23', '', NULL, '修改KPI-重置按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3813, '修改KPI-取消', 3810, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_kpi_close_update', '#', 'admin', '2022-03-24 10:49:23', '', NULL, '修改KPI-取消按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3814, 'KPI列表', 3804, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_kpi', '#', 'admin', '2022-03-24 10:49:23', '', NULL, 'KPI列表按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3815, 'KPI列表-新建', 3814, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_kpi_create', '#', 'admin', '2022-03-24 10:49:23', '', NULL, 'KPI列表-新建按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3816, 'KPI列表-修改', 3814, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_kpi_update', '#', 'admin', '2022-03-24 10:49:23', '', NULL, 'KPI列表-修改按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3817, 'KPI列表-删除', 3814, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_kpi_delete_inner', '#', 'admin', '2022-03-24 10:49:23', '', NULL, 'KPI列表-删除按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3819, 'KPI列表-删除', 3814, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_kpi_delete_top', '#', 'admin', '2022-03-24 10:49:23', '', NULL, 'KPI列表-删除按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3820, '查询KPI', 3804, 3, '', NULL, NULL, 1, 0, 'F', '0', '0', 's0_rva_kpi', '#', 'admin', '2022-03-24 10:49:23', '', NULL, '查询KPI按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3821, '新建素材库', 3924, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_material', '#', 'admin', '2022-04-09 11:57:31', '', NULL, '新建素材库按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3822, '新建素材库-提交', 3821, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_material_submit_create', '#', 'admin', '2022-04-09 11:57:31', '', NULL, '新建素材库-提交按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3823, '新建素材库-重置', 3821, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_material_reset_create', '#', 'admin', '2022-04-09 11:57:31', '', NULL, '新建素材库-重置按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3824, '新建素材库-取消', 3821, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_material_close_create', '#', 'admin', '2022-04-09 11:57:31', '', NULL, '新建素材库-取消按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3825, '修改素材库', 3924, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_material', '#', 'admin', '2022-04-09 11:57:31', '', NULL, '修改素材库按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3826, '修改素材库-提交', 3825, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_material_submit_update', '#', 'admin', '2022-04-09 11:57:31', '', NULL, '修改素材库-提交按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3827, '修改素材库-重置', 3825, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_material_reset_update', '#', 'admin', '2022-04-09 11:57:31', '', NULL, '修改素材库-重置按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3829, '修改素材库-取消', 3825, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_material_close_update', '#', 'admin', '2022-04-09 11:57:31', '', NULL, '修改素材库-取消按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3830, '素材库列表', 3924, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_material', '#', 'admin', '2022-04-09 11:57:31', '', NULL, '素材库列表按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3831, '素材库列表-新建', 3830, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_material_create', '#', 'admin', '2022-04-09 11:57:31', '', NULL, '素材库列表-新建按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3832, '素材库列表-修改', 3830, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_material_update', '#', 'admin', '2022-04-09 11:57:31', '', NULL, '素材库列表-修改按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3833, '素材库列表-删除', 3830, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_material_delete_inner', '#', 'admin', '2022-04-09 11:57:31', '', NULL, '素材库列表-删除按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3834, '素材库列表-删除', 3830, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_material_delete_top', '#', 'admin', '2022-04-09 11:57:31', '', NULL, '素材库列表-删除按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3835, '查询素材库', 3924, 3, '', NULL, NULL, 1, 0, 'F', '0', '0', 's0_rva_material', '#', 'admin', '2022-04-09 11:57:31', '', NULL, '查询素材库按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3836, '移动应用', 0, 5, 'rva_uniapp', NULL, NULL, 1, 0, 'M', '0', '0', NULL, 'phone', 'admin', '2022-05-12 18:36:52', '', NULL, '');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3837, '移动应用', 3836, 0, 'crud0_rva_uniapp', 'rva/app/crud', NULL, 1, 0, 'C', '0', '0', 'crud0_rva_uniapp', 'phone', '1', '2022-05-12 18:39:13', '1', '2022-05-12 18:39:13', NULL);\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3838, '新建移动应用', 3837, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_uniapp', '#', 'admin', '2022-05-12 18:39:13', '', NULL, '新建移动应用按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3839, '新建移动应用-提交', 3838, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_uniapp_submit_create', '#', 'admin', '2022-05-12 18:39:13', '', NULL, '新建移动应用-提交按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3840, '新建移动应用-重置', 3838, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_uniapp_reset_create', '#', 'admin', '2022-05-12 18:39:13', '', NULL, '新建移动应用-重置按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3841, '新建移动应用-取消', 3838, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_uniapp_close_create', '#', 'admin', '2022-05-12 18:39:13', '', NULL, '新建移动应用-取消按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3842, '修改移动应用', 3837, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_uniapp', '#', 'admin', '2022-05-12 18:39:13', '', NULL, '修改移动应用按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3843, '修改移动应用-提交', 3842, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_uniapp_submit_update', '#', 'admin', '2022-05-12 18:39:13', '', NULL, '修改移动应用-提交按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3844, '修改移动应用-重置', 3842, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_uniapp_reset_update', '#', 'admin', '2022-05-12 18:39:13', '', NULL, '修改移动应用-重置按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3845, '修改移动应用-取消', 3842, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_uniapp_close_update', '#', 'admin', '2022-05-12 18:39:13', '', NULL, '修改移动应用-取消按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3846, '移动应用列表', 3837, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_uniapp', '#', 'admin', '2022-05-12 18:39:13', '', NULL, '移动应用列表按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3847, '移动应用列表-新建', 3846, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_uniapp_create', '#', 'admin', '2022-05-12 18:39:13', '', NULL, '移动应用列表-新建按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3848, '移动应用列表-修改', 3846, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_uniapp_update', '#', 'admin', '2022-05-12 18:39:13', '', NULL, '移动应用列表-修改按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3849, '移动应用列表-删除', 3846, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_uniapp_delete_inner', '#', 'admin', '2022-05-12 18:39:13', '', NULL, '移动应用列表-删除按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3850, '移动应用列表-删除', 3846, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_uniapp_delete_top', '#', 'admin', '2022-05-12 18:39:13', '', NULL, '移动应用列表-删除按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3851, '查询移动应用', 3837, 3, '', NULL, NULL, 1, 0, 'F', '0', '0', 's0_rva_uniapp', '#', 'admin', '2022-05-12 18:39:13', '', NULL, '查询移动应用按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3853, '应用消息', 3836, 0, 'crud0_rva_uniapp_msg', 'rva/app/crud', NULL, 1, 0, 'C', '0', '0', 'crud0_rva_uniapp_msg', 'message', '1', '2022-05-12 18:41:08', '1', '2022-05-12 18:41:08', NULL);\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3854, '新建应用消息表', 3853, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_uniapp_msg', '#', 'admin', '2022-05-12 18:41:08', '', NULL, '新建应用消息表按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3855, '新建应用消息表-提交', 3854, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_uniapp_msg_submit_create', '#', 'admin', '2022-05-12 18:41:08', '', NULL, '新建应用消息表-提交按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3856, '新建应用消息表-重置', 3854, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_uniapp_msg_reset_create', '#', 'admin', '2022-05-12 18:41:08', '', NULL, '新建应用消息表-重置按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3857, '新建应用消息表-取消', 3854, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_uniapp_msg_close_create', '#', 'admin', '2022-05-12 18:41:08', '', NULL, '新建应用消息表-取消按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3858, '修改应用消息表', 3853, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_uniapp_msg', '#', 'admin', '2022-05-12 18:41:08', '', NULL, '修改应用消息表按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3859, '修改应用消息表-提交', 3858, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_uniapp_msg_submit_update', '#', 'admin', '2022-05-12 18:41:08', '', NULL, '修改应用消息表-提交按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3860, '修改应用消息表-重置', 3858, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_uniapp_msg_reset_update', '#', 'admin', '2022-05-12 18:41:08', '', NULL, '修改应用消息表-重置按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3861, '修改应用消息表-取消', 3858, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_uniapp_msg_close_update', '#', 'admin', '2022-05-12 18:41:08', '', NULL, '修改应用消息表-取消按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3862, '应用消息表列表', 3853, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_uniapp_msg', '#', 'admin', '2022-05-12 18:41:08', '', NULL, '应用消息表列表按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3863, '应用消息表列表-新建', 3862, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_uniapp_msg_create', '#', 'admin', '2022-05-12 18:41:08', '', NULL, '应用消息表列表-新建按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3864, '应用消息表列表-修改', 3862, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_uniapp_msg_update', '#', 'admin', '2022-05-12 18:41:08', '', NULL, '应用消息表列表-修改按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3865, '应用消息表列表-删除', 3862, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_uniapp_msg_delete_inner', '#', 'admin', '2022-05-12 18:41:08', '', NULL, '应用消息表列表-删除按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3866, '应用消息表列表-删除', 3862, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_uniapp_msg_delete_top', '#', 'admin', '2022-05-12 18:41:08', '', NULL, '应用消息表列表-删除按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3867, '查询应用消息表', 3853, 3, '', NULL, NULL, 1, 0, 'F', '0', '0', 's0_rva_uniapp_msg', '#', 'admin', '2022-05-12 18:41:08', '', NULL, '查询应用消息表按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3868, '移动应用权限', 3836, 0, 'tcrud0_rva_uniapp_permission', 'rva/app/tcrud', NULL, 1, 0, 'C', '0', '0', 'tcrud0_rva_uniapp_permission', 'build', '1', '2022-05-12 19:03:02', 'admin', '2022-05-18 20:19:38', NULL);\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3869, '移动应用权限', 3868, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'crud1_rva_uniapp_permission', '#', 'admin', '2022-05-12 19:03:02', '', NULL, '移动应用权限按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3870, '新建移动应用权限', 3869, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c1_rva_uniapp_permission', '#', 'admin', '2022-05-12 19:03:02', '', NULL, '新建移动应用权限按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3871, '新建移动应用权限-提交', 3870, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c1_rva_uniapp_permission_submit_create', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '新建移动应用权限-提交按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3872, '新建移动应用权限-重置', 3870, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c1_rva_uniapp_permission_reset_create', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '新建移动应用权限-重置按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3874, '修改移动应用权限', 3869, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u1_rva_uniapp_permission', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '修改移动应用权限按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3875, '修改移动应用权限-提交', 3874, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u1_rva_uniapp_permission_submit_update', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '修改移动应用权限-提交按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3876, '修改移动应用权限-重置', 3874, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u1_rva_uniapp_permission_reset_update', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '修改移动应用权限-重置按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3877, '修改移动应用权限-取消', 3874, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u1_rva_uniapp_permission_close_update', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '修改移动应用权限-取消按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3878, '移动应用权限列表', 3869, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l1_rva_uniapp_permission', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '移动应用权限列表按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3879, '移动应用权限列表-新建', 3878, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l1_rva_uniapp_permission_create', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '移动应用权限列表-新建按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3880, '移动应用权限列表-修改', 3878, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l1_rva_uniapp_permission_update', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '移动应用权限列表-修改按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3881, '移动应用权限列表-删除', 3878, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l1_rva_uniapp_permission_delete_inner', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '移动应用权限列表-删除按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3882, '移动应用权限列表-删除', 3878, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l1_rva_uniapp_permission_delete_top', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '移动应用权限列表-删除按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3883, '查询移动应用权限', 3869, 3, '', NULL, NULL, 1, 0, 'F', '0', '0', 's1_rva_uniapp_permission', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '查询移动应用权限按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3884, '移动应用权限', 3868, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'crud0_rva_uniapp_permission', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '移动应用权限按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3885, '新建移动应用权限', 3884, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_uniapp_permission', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '新建移动应用权限按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3886, '新建移动应用权限-提交', 3885, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_uniapp_permission_submit_create', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '新建移动应用权限-提交按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3887, '新建移动应用权限-重置', 3885, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_uniapp_permission_reset_create', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '新建移动应用权限-重置按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3888, '新建移动应用权限-取消', 3885, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c0_rva_uniapp_permission_close_create', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '新建移动应用权限-取消按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3889, '修改移动应用权限', 3884, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_uniapp_permission', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '修改移动应用权限按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3890, '修改移动应用权限-提交', 3889, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_uniapp_permission_submit_update', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '修改移动应用权限-提交按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3891, '修改移动应用权限-重置', 3889, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_uniapp_permission_reset_update', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '修改移动应用权限-重置按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3892, '修改移动应用权限-取消', 3889, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'u0_rva_uniapp_permission_close_update', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '修改移动应用权限-取消按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3893, '移动应用权限列表', 3884, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_uniapp_permission', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '移动应用权限列表按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3894, '移动应用权限列表-新建', 3893, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_uniapp_permission_create', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '移动应用权限列表-新建按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3895, '移动应用权限列表-修改', 3893, 0, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_uniapp_permission_update', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '移动应用权限列表-修改按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3896, '移动应用权限列表-删除', 3893, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_uniapp_permission_delete_inner', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '移动应用权限列表-删除按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3897, '移动应用权限列表-删除', 3893, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'l0_rva_uniapp_permission_delete_top', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '移动应用权限列表-删除按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3900, '查询移动应用权限', 3889, 3, '', NULL, NULL, 1, 0, 'F', '0', '0', 's0_rva_uniapp_permission', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '查询移动应用权限按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3901, '新建移动应用权限-取消', 3870, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'c1_rva_uniapp_permission_close_create', '#', 'admin', '2022-05-12 19:03:03', '', NULL, '新建移动应用权限-取消按钮');\n" +
                "INSERT INTO `ry-vue`.`sys_menu`(`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3924, '素材库', 3696, 0, 'crud0_rva_material', 'rva/app/crud', NULL, 1, 0, 'C', '0', '0', 'crud0_rva_material', 'build', '1', '2022-03-23 16:44:35', '1', '2022-03-23 16:44:35', NULL);\n";
        Integer[] ids = {2477
                ,3696
                ,3712
                ,3713
                ,3717
                ,3721
                ,3727
                ,3728
                ,3729
                ,3733
                ,3737
                ,3789
                ,3790
                ,3794
                ,3798
                ,3804
                ,3805
                ,3810
                ,3814
                ,3821
                ,3825
                ,3830
                ,3836
                ,3837
                ,3838
                ,3842
                ,3846
                ,3853
                ,3854
                ,3858
                ,3862
                ,3868
                ,3869
                ,3870
                ,3874
                ,3878
                ,3884
                ,3885
                ,3889
                ,3893
                ,3924};
        Integer start = 1100;
        for (Integer id : ids
        ) {
            txt = txt.replaceAll(id + "", start + "");
            start++;
        }

        System.out.println("result=======");
        System.out.println(txt);
        if (true) {
            return;
        }

        // Endpoint以华东1（杭州）为例，其它Region请按实际情况填写。
        // 填写Object完整路径，完整路径中不能包含Bucket名称，例如exampledir/exampleobject.txt。
        String objectName = "test/test.jpeg";
        // 填写本地文件的完整路径，例如D:\\localpath\\examplefile.txt。
        // 如果未指定本地路径，则默认从示例程序所属项目对应本地路径中上传文件流。
        //D:\cb9bf9a628f322627247ad9a03ce487e.jpeg
        String filePath = "D:\\cb9bf9a628f322627247ad9a03ce487e.jpeg";
        // 创建OSSClient实例。
        OSS ossClient = new OSSClientBuilder().build(endpoint, accessKeyId, accessKeySecret);

        try {
            InputStream inputStream = new FileInputStream(filePath);
            // 创建PutObject请求。
            ossClient.putObject(bucketName, objectName, inputStream);
        } catch (OSSException oe) {
            System.out.println("Caught an OSSException, which means your request made it to OSS, "
                    + "but was rejected with an error response for some reason.");
            System.out.println("Error Message:" + oe.getErrorMessage());
            System.out.println("Error Code:" + oe.getErrorCode());
            System.out.println("Request ID:" + oe.getRequestId());
            System.out.println("Host ID:" + oe.getHostId());
        } catch (ClientException ce) {
            System.out.println("Caught an ClientException, which means the client encountered "
                    + "a serious internal problem while trying to communicate with OSS, "
                    + "such as not being able to access the network.");
            System.out.println("Error Message:" + ce.getMessage());
        } finally {
            if (ossClient != null) {
                ossClient.shutdown();
            }
        }
    }
}
